/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1e",
        "on-tertiary-fixed": "#00201f",
        "on-primary": "#ffffff",
        "surface-variant": "#e3e2e6",
        "on-primary-fixed": "#001b3c",
        "tertiary-container": "#003d3c",
        "outline-variant": "#c4c6cf",
        "on-tertiary-container": "#4cadab",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e3e2e6",
        tertiary: "#002625",
        "surface-dim": "#dad9dd",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#596376",
        "on-primary-container": "#86a0cd",
        "primary-fixed": "#d6e3ff",
        "inverse-on-surface": "#f1f0f4",
        "surface-container": "#efedf1",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1e",
        surface: "#faf9fd",
        "surface-tint": "#455f88",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3033",
        "secondary-container": "#d6e0f6",
        "primary-container": "#1a365d",
        "on-secondary-fixed-variant": "#3d4759",
        secondary: "#555f71",
        error: "#ba1a1a",
        "primary-fixed-dim": "#adc7f7",
        "on-primary-fixed-variant": "#2d476f",
        "on-tertiary-fixed-variant": "#00504e",
        "tertiary-fixed": "#94f2f0",
        background: "#faf9fd",
        "tertiary-fixed-dim": "#77d6d3",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f3f7",
        "inverse-primary": "#adc7f7",
        "secondary-fixed-dim": "#bdc7dc",
        "on-secondary-fixed": "#121c2c",
        primary: "#002045",
        "surface-bright": "#faf9fd",
        outline: "#74777f",
        "on-surface-variant": "#43474e",
        "secondary-fixed": "#d9e3f9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        "stack-lg": "32px",
        unit: "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "stack-md": "16px",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
