import enum
from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base

EMBEDDING_DIM = 2560  # qwen3-embedding:4b


class ThesisSource(str, enum.Enum):
    professor = "professor"
    student = "student"
    openalex = "openalex"


class ThesisDifficulty(str, enum.Enum):
    bachelor = "bachelor"
    master = "master"
    phd = "phd"


class Thesis(Base):
    __tablename__ = "theses"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    abstract: Mapped[str] = mapped_column(Text, nullable=False)
    chair_id: Mapped[int | None] = mapped_column(
        ForeignKey("chairs.id", ondelete="SET NULL"), nullable=True, index=True
    )
    supervisor_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    submitter_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    source: Mapped[ThesisSource] = mapped_column(
        Enum(ThesisSource, name="thesis_source"), nullable=False
    )
    difficulty: Mapped[ThesisDifficulty | None] = mapped_column(
        Enum(ThesisDifficulty, name="thesis_difficulty"), nullable=True
    )
    # JSON: {programming: [...], math: [...], theory: [...], domain: [...], other: [...]}
    skills_required: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    # Set when the thesis was generated by the agent for a specific student.
    generated_for_user_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    # Which chat session triggered the generation.
    chat_session_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("chat_sessions.id", ondelete="SET NULL"), nullable=True
    )
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
